solution: DotNetBio.sln
language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
script:
  - cd Source/Bio.Core
  - dotnet build -c Release
  - cd ../Bio.Padena
  - dotnet build -c Release
  - cd ../Bio.Pamsam
  - dotnet build -c Release
  - cd ../../Tests/Bio.Tests
  - dotnet test
  - cd ../Bio.Pamsam.Tests
  - dotnet test
  - cd ../Bio.Padena.Tests
  - dotnet test